PortfolioData = [
    {
        "img": "https://s3-eu-west-1.amazonaws.com//bierapp/beers/thumb_5321dfdbf6b0748c03000006.jpg",
        "name": "umap",
        "techniques": [
            "Ruby on Rails",
            "Javascript",
            "SVG",
            "raphael.js",
            "HTML5",
            "D3.js",
            "Linear Algebra",
            "Nearest Neighbour Algorithm",
            "MongoDB",
            "postgreSQL",
            "Data Visualisation"
        ],
        "data product": "Together with the Center for Higher Educational Policy Studies, an institute linked to University Twente, we developed a web application that maps universities on 29 dimensions. The data application we developed lets you search, filter and compare universities on all of these dimensions. Furthermore, the back-end is fully equiped for gathering standardized information about higher educational institutions in countries with differ-ent traditions and ways of presenting their data. The U-map application validates data input thoroughly.",
        "intelligent": "There is a lot of information In the 29 dimensional data of all universities. This data encloses connections between uni-versities never seen before. We devel-oped a simple but efficient algorithm to discover and compare universities based on similarity.",
        "insights": "The multidimensional classification is presented in an interactive and simple way.",
        "href": "www.u-map.org",
        "hours": 50,
        "x_pos": 150,
        "y_pos": 300,
        size: 50,
        y_mid: 25,
        "color": "red",
        index: 1
    },
        {
        "img": "https://s3-eu-west-1.amazonaws.com//bierapp/beers/thumb_5321dfdbf6b0748c03000006.jpg",
        "name": "test",
        "techniques": [
            "Ruby on Rails",
            "Javascript",
            "SVG",
            "raphael.js",
            "HTML5",
            "D3.js",
            "Linear Algebra",
            "Nearest Neighbour Algorithm",
            "MongoDB",
            "postgreSQL",
            "Data Visualisation"
        ],
        "data product": "Together with the Center for Higher Educational Policy Studies, an institute linked to University Twente, we developed a web application that maps universities on 29 dimensions. The data application we developed lets you search, filter and compare universities on all of these dimensions. Furthermore, the back-end is fully equiped for gathering standardized information about higher educational institutions in countries with differ-ent traditions and ways of presenting their data. The U-map application validates data input thoroughly.",
        "intelligent": "There is a lot of information In the 29 dimensional data of all universities. This data encloses connections between uni-versities never seen before. We devel-oped a simple but efficient algorithm to discover and compare universities based on similarity.",
        "insights": "The multidimensional classification is presented in an interactive and simple way.",
        "href": "www.u-map.org",
        "hours": 1000,
        "x_pos": 300,
        "y_pos": 100,
        size: 100,
        y_mid: 50,
        "color": "blue",
        index: 2
    },
        {
        "img": "https://s3-eu-west-1.amazonaws.com//bierapp/beers/thumb_5321dfdbf6b0748c03000006.jpg",
        "name": "test",
        "techniques": [
            "Ruby on Rails",
            "Javascript",
            "SVG",
            "raphael.js",
            "HTML5",
            "D3.js",
            "Linear Algebra",
            "Nearest Neighbour Algorithm",
            "MongoDB",
            "postgreSQL",
            "Data Visualisation"
        ],
        "data product": "Together with the Center for Higher Educational Policy Studies, an institute linked to University Twente, we developed a web application that maps universities on 29 dimensions. The data application we developed lets you search, filter and compare universities on all of these dimensions. Furthermore, the back-end is fully equiped for gathering standardized information about higher educational institutions in countries with differ-ent traditions and ways of presenting their data. The U-map application validates data input thoroughly.",
        "intelligent": "There is a lot of information In the 29 dimensional data of all universities. This data encloses connections between uni-versities never seen before. We devel-oped a simple but efficient algorithm to discover and compare universities based on similarity.",
        "insights": "The multidimensional classification is presented in an interactive and simple way.",
        "href": "www.u-map.org",
        "hours": 5000,
        "x_pos": 450,
        "y_pos": 200,
        size: 200,
        y_mid: 100,
        "color": "purple",
        index: 3
    },
        {
        "img": "https://s3-eu-west-1.amazonaws.com//bierapp/beers/thumb_5321dfdbf6b0748c03000006.jpg",
        "name": "test",
        "techniques": [
            "Ruby on Rails",
            "Javascript",
            "SVG",
            "raphael.js",
            "HTML5",
            "D3.js",
            "Linear Algebra",
            "Nearest Neighbour Algorithm",
            "MongoDB",
            "postgreSQL",
            "Data Visualisation"
        ],
        "data product": "Together with the Center for Higher Educational Policy Studies, an institute linked to University Twente, we developed a web application that maps universities on 29 dimensions. The data application we developed lets you search, filter and compare universities on all of these dimensions. Furthermore, the back-end is fully equiped for gathering standardized information about higher educational institutions in countries with differ-ent traditions and ways of presenting their data. The U-map application validates data input thoroughly.",
        "intelligent": "There is a lot of information In the 29 dimensional data of all universities. This data encloses connections between uni-versities never seen before. We devel-oped a simple but efficient algorithm to discover and compare universities based on similarity.",
        "insights": "The multidimensional classification is presented in an interactive and simple way.",
        "href": "www.u-map.org",
        "hours": 5000,
        "x_pos": 600,
        "y_pos": 300,
        size: 200,
        y_mid: 100,
        "color": "orange",
        index: 4
    }
]
//edges: [
//{ source: 0, target: 1},
//{ source: 1, target: 2}
//]
