PortfolioData = [
    {
        img: "images/umap.png",
        name: "umap",
        techniques: [
            "Ruby on Rails",
            "CoffeeScript",
            "SVG",
            "raphael.js",
            "HTML5",
            "Linear Algebra",
            "Nearest Neighbour Algorithm",
            "MongoDB",
            "postgreSQL",
            "Data Visualisation"
        ],
        data_product: "Together with the Center for Higher Educational Policy Studies, an institute linked to University Twente, we developed a web application that maps universities on 29 dimensions. The data application we developed lets you search, filter and compare universities on all of these dimensions. Furthermore, the back-end is fully equiped for gathering standardized information about higher educational institutions in countries with differ-ent traditions and ways of presenting their data. The U-map application validates data input thoroughly.",
        intelligent: "There is a lot of information In the 29 dimensional data of all universities. This data encloses connections between uni-versities never seen before. We devel-oped a simple but efficient algorithm to discover and compare universities based on similarity.",
        insights: "The multidimensional classification is presented in an interactive and simple way.",
        website: "www.u-map.org",
        hours: 50,
        x: 18,
        y: 15,
        r: 10,
        color: "#29abe2",
        index: 1
    },
        {
        img: "images/mozart2.png",
        name: "Mozart",
        techniques: [
            "Hadoop",
            "Pig",
            "Julia",
            "Python",
            "MongoDB",
            "Meteor",
            "d3.js",
            "charts.js",
            "CoffeeScript",
            "Bayesian classifiers",
            "Lucene"
        ],
        data_product: "Mozart is being developed in deep collaboration with market research company DVJ insights. On one side we directly listen to open sources like Twitter, Facebook and Last.FM to learn what people are saying. We combine this with specialized information from radio airplay, spotify and youtube. The last piece of information comes from a large user panel. We sample feedback from users about what they like.",
        intelligent: "There is a lot of information In the 29 dimensional data of all universities. This data encloses connections between uni-versities never seen before. We devel-oped a simple but efficient algorithm to discover and compare universities based on similarity.",
        insights: "The multidimensional classification is presented in an interactive and simple way.",
        website: "www.u-map.org",
        hours: 1000,
        x: 40,
        y: 10,
        r: 7,
        color: "rgba(65, 0, 80, 1)",
        index: 2
    },
        {
        img: "images/bierapp.png",
        name: "BierApp",
        techniques: [
            "Objective-C",
            "Java",
            "Ruby on Rails",
            "Javascript",
            "MongoDB",
            "Machine Learning",
            "Bayesian Sets",
            "Collaborative Filters",
            "Bayesian classifiers"
        ],
        data_product: "Discover your favorite beer, know where this beer is served and build your personal beer journal; This is the BierApp. It gives you advice on what to drink next and shows the beer listings of café’s. The 'BierApp' makes sure you always drink the right beer on the right occasion.",
        intelligent: "There is a lot of information In the 29 dimensional data of all universities. This data encloses connections between uni-versities never seen before. We devel-oped a simple but efficient algorithm to discover and compare universities based on similarity.",
        insights: "The multidimensional classification is presented in an interactive and simple way.",
        website: "www.u-map.org",
        hours: 5000,
        x: 60,
        y: 25,
        r: 8,
        y_mid: 100,
        color: "rgba(156, 38, 21, 1)",
        index: 3
    },
        {
        img: "images/kplusv.png",
        name: "KplusV",
        techniques: [
            "Ruby on Rails",
            "Javascript",
            "d3.js",
            "Linear Algebra",
            "MongoDB",
            "Data Visualisation"
        ],
        data_product: "In co-creation with KplusV we developed a web application, which maps the vitality of a cultural organisation. By means of a questionnaire we measure innovativity, distinctiveness, strategy and business execution. When the questionnaire is finished, the application presents a diagnosis.",
        intelligent: "There is a lot of information In the 29 dimensional data of all universities. This data encloses connections between uni-versities never seen before. We devel-oped a simple but efficient algorithm to discover and compare universities based on similarity.",
        insights: "The multidimensional classification is presented in an interactive and simple way.",
        website: "www.u-map.org",
        hours: 5000,
        x: 80,
        y: 20,
        r: 5,
        y_mid: 100,
        color: "rgba(147, 185, 75, 1)",
        index: 4
    }
]
